# Generated by Django 4.2.1 on 2023-06-23 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loans', '0002_loan_delete_loans'),
    ]

    operations = [
        migrations.CreateModel(
            name='loanValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('payment_amout', models.FloatField()),
                ('interest', models.FloatField()),
                ('principle', models.FloatField()),
                ('balance', models.FloatField()),
                ('loan_amount', models.ForeignKey(db_column='loan_amount', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_loan_amount', to='loans.loan')),
                ('loan_id', models.ForeignKey(db_column='loan_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_loan_id', to='loans.loan')),
            ],
        ),
    ]
