# Generated by Django 4.2.1 on 2023-07-14 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanvalues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanvalue',
            name='interest_paid_date',
            field=models.DateField(null=True),
        ),
    ]
