# Generated by Django 4.2.1 on 2023-06-24 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanValues', '0002_remove_loanvalue_id_remove_loanvalue_loan_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanvalue',
            name='payment_ID',
        ),
        migrations.AddField(
            model_name='loanvalue',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
