# Generated by Django 4.2.1 on 2023-07-14 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_alter_loan_loaned_date'),
        ('loanvalues', '0002_loanvalue_interest_paid_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanvalue',
            name='loan_number',
            field=models.ForeignKey(db_column='loan_number', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='customer_loan_number', to='loans.loan'),
        ),
    ]
