# Generated by Django 4.2.1 on 2023-06-24 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loanValues', '0003_remove_loanvalue_payment_id_loanvalue_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanvalue',
            name='loan_amount',
        ),
    ]
