# Generated by Django 4.2.1 on 2023-07-20 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_collector',
            field=models.BooleanField(default=False),
        ),
    ]
