# Generated by Django 4.2.1 on 2023-07-11 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='usertype',
            field=models.CharField(choices=[('staff', 'staff'), ('customer', 'customer'), ('manager', 'manager')], default='customer', max_length=10),
        ),
    ]
