# Generated by Django 4.2.1 on 2023-07-11 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_usertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='usertype',
            field=models.CharField(choices=[('customer', 'customer'), ('staff', 'staff'), ('manager', 'manager')], default='customer', max_length=10),
        ),
    ]
