# Generated by Django 4.2.1 on 2023-07-30 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_alter_analytics_loan_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='analytics',
            name='calculated_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='analytics',
            name='total_loanArrears_accounts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analytics',
            name='total_payments',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
