# Generated by Django 4.2.1 on 2023-07-31 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_analytics_monthly_customer_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='analytics',
            name='date_requested',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
