# Generated by Django 4.2.1 on 2023-07-31 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_analytics_date_requested'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analytics',
            old_name='monthly_customer_count',
            new_name='lastmonth_customer_count',
        ),
    ]
