# Generated by Django 4.2.1 on 2023-06-15 03:00

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('surname', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('telephone1', models.CharField(max_length=100)),
                ('telephone2', models.CharField(max_length=100)),
                ('dateofbirth', models.DateField(null=True)),
                ('nicnumber', models.CharField(max_length=100)),
                ('branch', models.CharField(choices=[('Polonnaruwa', 'Polonnaruwa'), ('Hingurakgoda', 'Hingurakgoda'), ('Diyasenpura', 'Diyasenpura'), ('Sewanapitiya', 'Sewanapitiya'), ('Dehiaththakandiya', 'Dehiaththakandiya'), ('Mahiyanganaya', 'Mahiyanganaya')], default='Sewanapitiya', max_length=20)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('users.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
