# Generated by Django 4.2.1 on 2023-07-20 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerProfile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='nic_image',
            field=models.FileField(blank=True, null=True, upload_to='hasaru/nic_images'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='hasaru/profile_images'),
        ),
    ]
