# Generated by Django 4.2.1 on 2023-07-20 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerProfile', '0002_customerprofile_nic_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerprofile',
            old_name='nic_image',
            new_name='nic_image_back',
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='nic_image_front',
            field=models.FileField(blank=True, null=True, upload_to='hasaru/nic_images'),
        ),
    ]
