# Generated by Django 4.2.1 on 2023-07-31 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerProfile', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='nicimageback',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='nicimagefront',
        ),
    ]
