# Generated by Django 4.2.1 on 2023-07-20 08:46

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerProfile', '0003_rename_nic_image_customerprofile_nic_image_back_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='nic_image_back',
            field=models.FileField(blank=True, null=True, upload_to='nic_images'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='nic_image_front',
            field=models.FileField(blank=True, null=True, upload_to='nic_images'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
