# Generated by Django 4.2.1 on 2023-07-20 08:54

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerProfile', '0006_alter_customerprofile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='nic_image_back',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='nic_images'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='nic_image_front',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='nic_images'),
        ),
    ]
