# Generated by Django 4.2.1 on 2023-07-20 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerProfile', '0007_alter_customerprofile_nic_image_back_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerprofile',
            old_name='nic_image_back',
            new_name='nicimageback',
        ),
        migrations.RenameField(
            model_name='customerprofile',
            old_name='nic_image_front',
            new_name='nicimagefront',
        ),
        migrations.RenameField(
            model_name='customerprofile',
            old_name='profile_image',
            new_name='profileimage',
        ),
    ]
