# Generated by Django 4.2.1 on 2023-07-17 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StaffProfile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='assigned_location',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
