# Generated by Django 4.2.1 on 2023-07-20 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StaffProfile', '0002_staffprofile_assigned_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffprofile',
            name='is_collector',
        ),
    ]
