# Generated by Django 4.2.1 on 2023-06-01 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('customer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_surname', models.CharField(max_length=100)),
                ('customer_address', models.CharField(max_length=100)),
                ('customer_phone1', models.CharField(max_length=100)),
                ('customer_phone2', models.CharField(max_length=100)),
                ('customer_email', models.CharField(max_length=100)),
                ('customer_dateofbirth', models.DateField()),
                ('customer_nic', models.CharField(max_length=100)),
            ],
        ),
    ]
