# Generated by Django 4.2.1 on 2023-06-01 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='customer_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='customer_dateofbirth',
            new_name='dateofbirth',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='customer_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='customer_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='customer_nic',
            new_name='nicnumber',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='customer_phone1',
            new_name='surname',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='customer_phone2',
            new_name='telephone1',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='customer_surname',
            new_name='telephone2',
        ),
        migrations.AddField(
            model_name='customer',
            name='username',
            field=models.CharField(default=models.CharField(max_length=100), max_length=100),
        ),
    ]
