# Generated by Django 4.2.1 on 2023-06-01 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_rename_customer_address_customer_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='dateofbirth',
            field=models.DateField(null=True),
        ),
    ]
