# Generated by Django 4.2.1 on 2023-07-12 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('loan_id', models.AutoField(primary_key=True, serialize=False)),
                ('loan_number', models.CharField(blank=True, max_length=12, unique=True)),
                ('loaned_date', models.DateField(default='2020-01-01')),
                ('branch_location', models.CharField(choices=[('Polonnaruwa', 'Polonnaruwa'), ('Diyasenpura', 'Diyasenpura'), ('Sewanapitiya', 'Sewanapitiya'), ('Dehiaththakandiya', 'Dehiaththakandiya'), ('Mahiyanaganaya', 'Mahiyanaganaya')], max_length=20)),
                ('loaned_amount', models.FloatField()),
                ('bike_number', models.CharField(max_length=12)),
                ('loan_period', models.IntegerField()),
                ('first_guarantor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_guarantor', to=settings.AUTH_USER_MODEL)),
                ('second_guarantor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_guarantor', to=settings.AUTH_USER_MODEL)),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
