# Generated by Django 4.2.1 on 2023-07-30 12:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('StaffProfile', '0001_initial'),
        ('loans', '0001_initial'),
        ('loanvalues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='loanarrears',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_payment', models.FloatField()),
                ('monthly_arrears', models.FloatField()),
                ('arr_cal_date', models.DateField(default=django.utils.timezone.now)),
                ('additional_fees', models.FloatField(default=0)),
                ('loan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loanarrears', to='loans.loan')),
                ('loan_values', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loanarrears', to='loanvalues.loanvalue')),
                ('staff', models.ForeignKey(default=4, on_delete=django.db.models.deletion.DO_NOTHING, related_name='loanarrears', to='StaffProfile.staffprofile')),
            ],
        ),
    ]
