# Generated by Django 4.2.1 on 2023-07-14 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loanarrears', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanarrears',
            old_name='loan_id',
            new_name='loan',
        ),
    ]
