# Generated by Django 4.2.1 on 2023-07-14 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loanarrears', '0002_rename_loan_id_loanarrears_loan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanarrears',
            old_name='loan',
            new_name='loan_id',
        ),
    ]
