# Generated by Django 4.2.1 on 2023-07-15 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanarrears', '0004_loanarrears_arr_cal_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanarrears',
            name='additional_fees',
            field=models.FloatField(null=True),
        ),
    ]
