# Generated by Django 4.2.1 on 2023-07-15 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StaffProfile', '0001_initial'),
        ('loanarrears', '0005_loanarrears_additional_fees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanarrears',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='loanarrears', to='StaffProfile.staffprofile'),
        ),
    ]
