# Generated by Django 4.2.1 on 2023-07-16 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanarrears', '0006_alter_loanarrears_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanarrears',
            name='additional_fees',
            field=models.FloatField(default=0, null=True),
        ),
    ]
