# Generated by Django 4.2.1 on 2023-07-16 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanarrears', '0007_alter_loanarrears_additional_fees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanarrears',
            name='additional_fees',
            field=models.FloatField(default=0),
        ),
    ]
