# Generated by Django 4.2.1 on 2023-07-21 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StaffProfile', '0003_remove_staffprofile_is_collector'),
        ('loanvalues', '0003_alter_loanvalue_loan_number'),
        ('loanarrears', '0008_alter_loanarrears_additional_fees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanarrears',
            name='loan_values',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loanarrears', to='loanvalues.loanvalue'),
        ),
        migrations.AlterField(
            model_name='loanarrears',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loanarrears', to='StaffProfile.staffprofile'),
        ),
    ]
