# Generated by Django 4.2.1 on 2023-07-28 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StaffProfile', '0003_remove_staffprofile_is_collector'),
        ('loanarrears', '0009_alter_loanarrears_loan_values_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanarrears',
            name='staff',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.DO_NOTHING, related_name='loanarrears', to='StaffProfile.staffprofile'),
        ),
    ]
