# Generated by Django 4.2.1 on 2023-06-15 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loans',
            fields=[
                ('loan_id', models.IntegerField(primary_key=True, serialize=False)),
                ('loan_name', models.CharField(max_length=100)),
                ('loan_amount', models.FloatField()),
            ],
        ),
    ]
