# Generated by Django 4.2.1 on 2023-07-30 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CustomerProfile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('loan_id', models.AutoField(primary_key=True, serialize=False)),
                ('loan_number', models.CharField(blank=True, max_length=12, unique=True)),
                ('loaned_date', models.DateField()),
                ('branch_location', models.CharField(choices=[('Polonnaruwa', 'Polonnaruwa'), ('Diyasenpura', 'Diyasenpura'), ('Sewanapitiya', 'Sewanapitiya'), ('Dehiaththakandiya', 'Dehiaththakandiya'), ('Mahiyanaganaya', 'Mahiyanaganaya')], max_length=20)),
                ('loaned_amount', models.FloatField()),
                ('bike_number', models.CharField(max_length=12)),
                ('loan_period', models.IntegerField()),
                ('first_guarantor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_guarantor', to='CustomerProfile.customerprofile')),
                ('second_guarantor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_guarantor', to='CustomerProfile.customerprofile')),
                ('username', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='CustomerProfile.customerprofile')),
            ],
        ),
    ]
