# Generated by Django 4.2.1 on 2023-06-22 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('loan_id', models.IntegerField(primary_key=True, serialize=False)),
                ('loan_name', models.CharField(max_length=100)),
                ('branch_location', models.CharField(choices=[('polonnaruwa', 'Polonnaruwa'), ('diyasenpura', 'Diyasenpura'), ('sewanapitiya', 'Sewanapitiya'), ('dehiaththakandiya', 'Dehiaththakandiya'), ('mahiyanaganaya', 'Mahiyanaganaya')], max_length=20)),
                ('loan_amount', models.FloatField()),
                ('bike_number', models.CharField(max_length=12)),
                ('first_guarantor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_guarantor', to=settings.AUTH_USER_MODEL)),
                ('second_guarantor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_guarantor', to=settings.AUTH_USER_MODEL)),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Loans',
        ),
    ]
