# Generated by Django 4.2.1 on 2023-06-23 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_loan_delete_loans'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='loaned_date',
            field=models.DateField(default='2020-01-01'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
