# Generated by Django 4.2.1 on 2023-07-14 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_alter_loan_first_guarantor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loaned_date',
            field=models.DateField(),
        ),
    ]
