# Generated by Django 4.2.1 on 2023-06-23 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_loan_loaned_date_alter_loan_loan_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='loan_amount',
            new_name='loaned_amount',
        ),
    ]
