# Generated by Django 4.2.1 on 2023-07-27 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerProfile', '0008_rename_nic_image_back_customerprofile_nicimageback_and_more'),
        ('loans', '0004_alter_loan_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='username',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='CustomerProfile.customerprofile'),
        ),
    ]
