# Generated by Django 4.2.1 on 2023-06-23 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_rename_loan_amount_loan_loaned_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='loan_name',
        ),
        migrations.AlterField(
            model_name='loan',
            name='branch_location',
            field=models.CharField(choices=[('Polonnaruwa', 'Polonnaruwa'), ('Diyasenpura', 'Diyasenpura'), ('Sewanapitiya', 'Sewanapitiya'), ('Dehiaththakandiya', 'Dehiaththakandiya'), ('Mahiyanaganaya', 'Mahiyanaganaya')], max_length=20),
        ),
    ]
