# Generated by Django 4.2.1 on 2023-06-24 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0006_loan_loan_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_number',
            field=models.CharField(blank=True, max_length=12, unique=True),
        ),
    ]
